### ISSUE TITLE
Issue with running the python GUI

### ISSUE THREAD

**Issue by gufunkt-tacos** [warber0x/FMPUNO#2]
Whenever I try to run the code it outputs this error.

`C:\Users\Administrator\Downloads\FMPUNO-master\FMPUNO-master\GUI_python3>python FlashMemoryProgrammer_GUI.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\FMPUNO-master\FMPUNO-master\GUI_python3\FlashMemoryProgrammer_GUI.py", line 852, in <module>
    thread1 = starter(1, 'Thread-1', 1)
  File "C:\Users\Administrator\Downloads\FMPUNO-master\FMPUNO-master\GUI_python3\FlashMemoryProgrammer_GUI.py", line 840, in __init__
    frame = programmer_gui(parent=None, id=-1)
  File "C:\Users\Administrator\Downloads\FMPUNO-master\FMPUNO-master\GUI_python3\FlashMemoryProgrammer_GUI.py", line 93, in __init__
    font3 = wx.Font(12, wx.NORMAL, wx.ITALIC, wx.BOLD)
wx._core.wxAssertionError: C++ assertion ""ff_family != (0<<4)"" failed at ..\..\src\msw\font.cpp(624) in wxNativeFontInfo::SetFamily(): unknown wxFontFamily`

I've installed PubSub and wxPython. My python version is 3.9.1 and I have the same error with 3.9.13.

**Comment by TheR3d0ne** [comment]
@gufunkt-tacos check this out [https://stackoverflow.com/questions/5278884/fonts-problem-when-switching-from-wxpython-2-8-to-2-9](https://stackoverflow.com/questions/5278884/fonts-problem-when-switching-from-wxpython-2-8-to-2-9). It's 
 a wxPython version problem. Otherwise, you can modify the code to be aligned with your version.
